const marketData = [
  {
    symbol: "PMGOLD.AX",
    name: "Perth Mint Gold",
    price: 17.94,
    exchange: "Australian Securities Exchange",
    exchangeShortName: "ASX",
    type: "etf",
  },
  {
    symbol: "DEA",
    name: "Easterly Government Properties, Inc.",
    price: 13.81,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "SPLG",
    name: "SPDR Portfolio S&P 500 ETF",
    price: 68.2825,
    exchange: "New York Stock Exchange Arca",
    exchangeShortName: "AMEX",
    type: "etf",
  },
  {
    symbol: "WLK",
    name: "Westlake Corporation",
    price: 133.12,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "BXP",
    name: "Boston Properties, Inc.",
    price: 82.6,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "NEE",
    name: "NextEra Energy, Inc.",
    price: 79.26,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "CHRW",
    name: "C.H. Robinson Worldwide, Inc.",
    price: 109.62,
    exchange: "NASDAQ Global Select",
    exchangeShortName: "NASDAQ",
    type: "stock",
  },
  {
    symbol: "LRCX",
    name: "Lam Research Corporation",
    price: 76.64,
    exchange: "NASDAQ Global Select",
    exchangeShortName: "NASDAQ",
    type: "stock",
  },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices, Inc.",
    price: 149.8977,
    exchange: "NASDAQ Global Select",
    exchangeShortName: "NASDAQ",
    type: "stock",
  },
  {
    symbol: "ACI",
    name: "Albertsons Companies, Inc.",
    price: 18.22,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "HOOD",
    name: "Robinhood Markets, Inc.",
    price: 28.415,
    exchange: "NASDAQ Global Select",
    exchangeShortName: "NASDAQ",
    type: "stock",
  },
  {
    symbol: "DOW",
    name: "Dow Inc.",
    price: 49.2262,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "PG",
    name: "The Procter & Gamble Company",
    price: 166.02,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "HLN",
    name: "Haleon plc",
    price: 9.835,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "MUR",
    name: "Murphy Oil Corporation",
    price: 31.49,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "NI",
    name: "NiSource Inc.",
    price: 35.19,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "STM",
    name: "STMicroelectronics N.V.",
    price: 27.705,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "ACN",
    name: "Accenture plc",
    price: 346.34,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "FUN",
    name: "Six Flags Entertainment Corporation",
    price: 41.57,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "LAZR",
    name: "Luminar Technologies, Inc.",
    price: 0.8211,
    exchange: "NASDAQ Global Select",
    exchangeShortName: "NASDAQ",
    type: "stock",
  },
  {
    symbol: "NU",
    name: "Nu Holdings Ltd.",
    price: 15.695,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "AMT",
    name: "American Tower Corporation",
    price: 213.2,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "PAAS",
    name: "Pan American Silver Corp.",
    price: 24.4545,
    exchange: "NASDAQ Global Select",
    exchangeShortName: "NASDAQ",
    type: "stock",
  },
  {
    symbol: "TSEM",
    name: "Tower Semiconductor Ltd.",
    price: 43.17,
    exchange: "NASDAQ Global Select",
    exchangeShortName: "NASDAQ",
    type: "stock",
  },
  {
    symbol: "KBR",
    name: "KBR, Inc.",
    price: 68.43,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "HASI",
    name: "Hannon Armstrong Sustainable Infrastructure Capital, Inc.",
    price: 34.7,
    exchange: "New York Stock Exchange",
    exchangeShortName: "NYSE",
    type: "stock",
  },
  {
    symbol: "BLKB",
    name: "Blackbaud, Inc.",
    price: 74.505,
    exchange: "NASDAQ Global Select",
    exchangeShortName: "NASDAQ",
    type: "stock",
  },
];

export default marketData;
